---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
# have to exclude third-party libs
exclude_paths:
- "client/css/lib/"
- "client/images/"
- "client/js/lib/"
- "developer_docs/"
- "docs/"
