# Travis CI Build Script
env:
  - SAUCE_USERNAME: "cprafullchandra"
  - SAUCE_ACCESS_KEY: "24bdca40-ec64-4241-bba3-b2a78d92f52d"
addons:
 code_climate:
    repo_token: ca1bce783e700880c07c8145d402e8f5cee54c5033f7bf88f51fc3e78e37e35e
 sauce_connect: true
notifications:
  slack: kissmyapp:ODLqzPLHklVTMNDvIF9VUSke
language: node_js
node_js:
  - "7"
services:
  - mongodb
script:
  - npm install
after_success:
  - npm install -g codeclimate-test-reporter
  - npm install -g codecov
  - npm run testback
  - npm run travisfront
  - npm run cover
  - codeclimate-test-reporter < coverage/lcov.info
  - codecov
deploy:
  provider: gae
  keyfile: kiss-my-app-29c0b19a8d6d.json
  project: kiss-my-app
  default: true
  skip_cleanup: true
  on:
    branch: develop
